.libPaths( c( "./sRNA_packages_R" , .libPaths() ))

install.packages("devtools", repos='http://cran.us.r-project.org')
require("devtools")

install_version("webshot2", version = "0.1.0", repos = "http://cran.us.r-project.org")
install_version("gt", version = "0.9.0", repos = "http://cran.us.r-project.org")
install_version("patchwork", version = "1.1.2", repos = "http://cran.us.r-project.org")
install_version("ggsci", version = "3.0.0", repos = "http://cran.us.r-project.org")
install_version("lubridate", version = "1.9.2", repos = "http://cran.us.r-project.org")
install_version("forcats", version = "1.0.0", repos = "http://cran.us.r-project.org")
install_version("stringr", version = "1.5.0", repos = "http://cran.us.r-project.org")
install_version("dplyr", version = "1.1.2", repos = "http://cran.us.r-project.org")
install_version("purrr", version = "1.0.1", repos = "http://cran.us.r-project.org")
install_version("readr", version = "2.1.4", repos = "http://cran.us.r-project.org")
install_version("tidyr", version = "1.3.0", repos = "http://cran.us.r-project.org")
install_version("tibble", version = "3.2.1", repos = "http://cran.us.r-project.org")
install_version("tidyverse", version = "2.0.0", repos = "http://cran.us.r-project.org")
install_version("ggpmisc", version = "0.5.2", repos = "http://cran.us.r-project.org")
install_version("ggpp", version = "0.5.2", repos = "http://cran.us.r-project.org")
install_version("ggplot2", version = "3.4.2", repos = "http://cran.us.r-project.org")

devtools::install_github("omarwagih/ggseqlogo")